name: Public Beta Release

on:
  push:
    tags: '*.*.*b*'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Branch Name for Tag
        id: get-branch
        run: |
          # Extract the branch name associated with the tag
          BRANCH_NAME=$(git name-rev --name-only "${{ github.ref_name }}")
          if [ -z "$BRANCH_NAME" ]; then
            echo "Failed to resolve branch name for the tag: ${{ github.ref_name }}."
            exit 1
          fi

          echo "Resolved Branch Name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Debug Resolved Branch
        run: |
          echo "Branch Name: ${{ env.branch_name }}"

      - name: Commit Changes to Resolved Branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # Checkout the resolved branch
          git checkout ${{ env.branch_name }}
          chmod +x ./bump_version.sh
          ./bump_version.sh "${{ github.ref_name }}"
          git add setup.py
          git commit -m "Update version for tag ${{ github.ref_name }}"
          # Push changes to the branch
          git push origin ${{ env.branch_name }}
